# Generated by Django 5.2.6 on 2025-09-30 18:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_id', models.CharField(help_text='OpenAI assistant ID', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField()),
                ('mode', models.CharField(help_text='Mode category (professional, personal, creative)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['mode', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(help_text='OpenAI thread ID', max_length=255, unique=True)),
                ('session_key', models.CharField(blank=True, help_text='Django session key', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assistant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'assistant'], name='app_chatthr_user_id_1398c5_idx'), models.Index(fields=['session_key', 'assistant'], name='app_chatthr_session_bc95db_idx'), models.Index(fields=['last_activity'], name='app_chatthr_last_ac_a81f55_idx')],
                'unique_together': {('session_key', 'assistant'), ('user', 'assistant')},
            },
        ),
    ]
