# Generated by Django 5.2.6 on 2025-09-30 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Django session key', max_length=40, null=True)),
                ('thread_id', models.CharField(help_text='OpenAI thread ID', max_length=255, unique=True)),
                ('title', models.CharField(blank=True, help_text='Chat title (auto-generated from first message)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this chat is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assistant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChatThread',
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'assistant'], name='app_chat_user_id_f747ec_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['session_key', 'assistant'], name='app_chat_session_fc3c11_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['last_activity'], name='app_chat_last_ac_317c78_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['is_active'], name='app_chat_is_acti_fdb61f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='app_chatmes_chat_id_cdc020_idx'),
        ),
    ]
