# Generated by Django 5.2.6 on 2025-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chat_chatmessage_delete_chatthread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='mode_id',
            field=models.CharField(default='', help_text='Mode identifier (e.g., teacher_tutor)', max_length=255, unique=True),
        ),
    ]
