# Generated by Django 5.2.6 on 2025-09-30 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_assistant_mode_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'assistant'), name='unique_active_user_assistant'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('session_key', 'assistant'), name='unique_active_session_assistant'),
        ),
    ]
