# Generated by Django 5.2.6 on 2025-09-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chat_unique_active_user_assistant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_active_user_assistant',
        ),
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_active_session_assistant',
        ),
    ]
