# Generated by Django 5.2.6 on 2025-09-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_chat_unique_active_user_assistant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='thread_id',
            field=models.CharField(help_text='OpenAI thread ID', max_length=255),
        ),
    ]
